[package]
name = "day9"
version = "0.1.0"
edition = "2021"

[lib]
name = "day9"
path = "src/lib.rs"

[[bin]]
name = "p1"
path = "src/p1.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }

[dev-dependencies]
tempfile = "3.14.0"
