[package]
name = "day7"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "p1"
path = "src/p1.rs"

[[bin]]
name = "p2"
path = "src/p2.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
