[package]
name = "day8"
version = "0.1.0"
edition = "2021"

[lib]
name = "day8"
path = "src/lib.rs"

[[bin]]
name = "p1"
path = "src/bin/p1.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
lazy_static = "1.5.0"
ndarray = "0.16.1"
